views/accesorio_view.py
from flask import Blueprint, render_template, request, redirect, url_for
from forms import AccesorioForm
from services.accesorio_service import AccesorioService

accesorio_bp = Blueprint('accesorio_bp', __name__)

@accesorio_bp.route("/accesorios_list", methods=["GET", "POST"])
def accesorios():
    accesorio_service = AccesorioService()
    accesorios = accesorio_service.get_all()

    formulario = AccesorioForm()

    if request.method == 'POST':
        if formulario.validate_on_submit():
            nombre = formulario.nombre.data
            accesorio_service.create(nombre)
            return redirect(url_for('accesorio_bp.accesorios'))
        # Si no es válido, renderiza el formulario con los errores
        return render_template('accesorios_list.html', accesorios=accesorios, formulario=formulario)

    return render_template('accesorios_list.html', accesorios=accesorios, formulario=formulario)

@accesorio_bp.route("/accesorio/<id>/eliminar", methods=['POST'])
def accesorio_eliminar(id):
    accesorio_service = AccesorioService()
    accesorio_service.delete(id)
    return redirect(url_for('accesorio_bp.accesorios'))

@accesorio_bp.route("/accesorio/<id>/editar", methods=['GET', 'POST'])
def accesorio_editar(id):
    accesorio_service = AccesorioService()
    accesorio = accesorio_service.get_by_id(id)

    formulario = AccesorioForm(obj=accesorio)

    if request.method == 'POST' and formulario.validate_on_submit():
        accesorio_service.update(id, formulario.nombre.data)
        return redirect(url_for('accesorio_bp.accesorios'))

    return render_template("accesorio_edit.html", accesorio=accesorio, formulario=formulario)

views/stock_view.py
from flask import Blueprint, render_template, request, redirect, url_for
from services.stock_services import obtener_stock_telefonos, agregar_stock, restar_stock
from forms import TelefonoCantidadForm
from app import db
from models import Stock ,Telefono
stock_bp = Blueprint('stock', __name__)

@stock_bp.route("/stock", methods=['GET', 'POST'])
def stock():
    telefonos = Telefono.query.all()

    if request.method == 'POST':
        telefono_id = request.form['telefono_id']
        cantidad = int(request.form['cantidad'])
        stock_item = Stock.query.filter_by(telefono_id=telefono_id).with_for_update().first()
        if stock_item:
            stock_item.cantidad += cantidad  
        else:
            nuevo_stock = Stock(telefono_id=telefono_id, cantidad=cantidad)  
            db.session.add(nuevo_stock)
        
        db.session.commit()
        return redirect(url_for('stock.stock'))

    telefonos_con_stock = []
    for telefono in telefonos:
        stock_item = Stock.query.filter_by(telefono_id=telefono.id).first()
        telefonos_con_stock.append({
            'telefono': telefono,
            'stock': stock_item.cantidad if stock_item else 0
        })

    return render_template('stock.html', telefonos=telefonos_con_stock)

@stock_bp.route("/restar_stock", methods=['POST'])
def restar_stock_view():
    form = TelefonoCantidadForm()
    if form.validate_on_submit():
        restar_stock(form.telefono.data, form.cantidad.data)
    return redirect(url_for('stock.stock'))

views/telefono_view.py
from flask import (
    Blueprint, 
    jsonify,
    redirect, 
    render_template, 
    request, 
    url_for, 
)
from services.telefono_service import TelefonoService 
from services.telefono_service import delete_with_accesorios

from repositories.telefono_repositories import TelefonoRepositories
from schemas import (
    AccesorioSchema,
    MarcaSchema, 
    TelefonoSchema, 
    TipoSchema, 
)
from models import (
    Accesorio, 
    Marca, 
    Tipo,
) 
from forms import TelefonoForm
from app import db

telefono_bp = Blueprint('telefono', __name__)

@telefono_bp.route("/telefono_list", methods=['POST', 'GET'])
def telefonos():
    telefono_service = TelefonoService(TelefonoRepositories())
    telefonos = telefono_service.get_all()

    telefono_schema = TelefonoSchema(many=True)
    telefonos_serializados = telefono_schema.dump(telefonos)

    marcas = Marca.query.all()
    tipos = Tipo.query.all()
    accesorios = Accesorio.query.all()

    formulario = TelefonoForm()
    
    try:
        formulario.marca.choices = [(marca.id, marca.nombre) for marca in marcas]
        formulario.tipo.choices = [(tipo.id, tipo.nombre) for tipo in tipos]
        formulario.accesorio.choices = [(accesorio.id, accesorio.nombre) for accesorio in accesorios]
    except Exception as e:
        return jsonify({"error": f"Error al cargar las opciones del formulario: {str(e)}"}), 500

    if request.method == 'POST' and formulario.validate_on_submit():
        try:
            modelo = formulario.modelo.data
            anio_fabricacion = formulario.anio_fabricacion.data
            precio = formulario.precio.data
            marca = formulario.marca.data
            tipo = formulario.tipo.data
            
            telefono_service.create(modelo, anio_fabricacion, precio, marca, tipo)
            return redirect(url_for('telefono.telefonos'))
        except Exception as e:
            return jsonify({"error": f"Error al crear el teléfono: {str(e)}"}), 500

    return render_template('telefono_list.html', 
                            telefonos=telefonos_serializados, 
                            formulario=formulario, 
                            marcas=marcas, 
                            tipos=tipos, 
                            accesorios=accesorios)

@telefono_bp.route("/telefono/<id>/eliminar", methods=['POST'])
def telefono_eliminar(id):
    telefono_service = TelefonoService(TelefonoRepositories())
    telefono_service.delete_with_accesorios(id)
    return redirect(url_for('telefono.telefonos'))


@telefono_bp.route("/telefono/<id>", methods=['GET'])
def telefono_accesorio(id):
    telefono_service = TelefonoService(TelefonoRepositories())
    accesorios = telefono_service.get_accesorios_by_telefono(id)
    telefono = telefono_service.get_by_id(id)

    return render_template("accesorios_by_telefono.html", telefono=telefono, accesorios=accesorios)


@telefono_bp.route('/telefono/<int:telefono_id>', methods=['DELETE'])
def delete_telefono(telefono_id):
    try:
        delete_with_accesorios(telefono_id)
        return jsonify({"message": "Teléfono eliminado con éxito"}), 200
    except Exception as e:
        db.session.rollback()  
        return jsonify({"error": str(e)}), 500

views/tipo_view.py
from flask import Blueprint, request, render_template, redirect, url_for
from services.tipo_service import TipoService
from repositories.tipo_repositories import TipoRepositories
from schemas import TipoSchema
from forms import TipoForm
from app import db

tipo_bp = Blueprint('tipo', __name__)

@tipo_bp.route("/tipo_list", methods=['GET', 'POST'])
def tipos():
    tipo_service = TipoService(TipoRepositories())
    tipos = tipo_service.get_all()

    tipo_schema = TipoSchema(many=True)
    tipos_serializados = tipo_schema.dump(tipos)

    formulario = TipoForm()
    if request.method == 'POST' and formulario.validate_on_submit():
        nombre = formulario.nombre.data
        tipo_service.create(nombre)
        return redirect(url_for('tipo.tipos'))

    return render_template('tipo_list.html', tipos=tipos_serializados, formulario=formulario)

@tipo_bp.route('/tipo/<int:id>/eliminar', methods=['POST'])
def tipo_eliminar(id):
    tipo_service = TipoService(TipoRepositories())
    tipo = tipo_service.get_by_id(id)
    if tipo:
        db.session.delete(tipo)
        db.session.commit()
        return redirect(url_for('tipo.tipos'))

templates/accesorio_edit.html
{% extends 'base_template.html' %}

{% block content %}
    <h4>Edite el Accesorio</h4>
    <form action="" method="post">
        <input type="text" name="nombre" value="{{accesorio.nombre}}">
        <button type="submit">Editar</button>
    </form>
{% endblock %}

templates/accesorios_by_telefono.html
{% extends 'base_template.html' %}

{% block content %}
<div class="container">
    <h4>Accesorios para el Teléfono: {{ telefono.modelo }}</h4>
    <ul>
        {% for accesorio in accesorios %}
            <li>{{ accesorio.nombre }}</li>
        {% else %}
            <li>No hay accesorios asociados.</li>
        {% endfor %}
    </ul>
    <a href="{{ url_for('telefonos') }}" class="btn btn-primary">Volver a la lista de teléfonos</a>
</div>
{% endblock %}

templates/accesorios_list.html
{% extends 'base_template.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>Crear un Nuevo Accesorio</h4>
            <form action="" method="POST">
                {{ formulario.hidden_tag() }}
                <div class="mb-3">
                    {{ formulario.nombre.label }}
                    {{ formulario.nombre(class="form-control") }}
                </div>
                <button type="submit" class="btn btn-success">Guardar</button>
            </form>
        </div>

        <div class="col-md-6">
            <h4>Listado de Accesorios</h4>
            <ul class="list-group">
                {% for accesorio in accesorios %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span>{{ accesorio.nombre }}</span>
                    <div>
                        <a href="{{ url_for('accesorio_bp.accesorio_editar', id=accesorio.id) }}" class="btn btn-warning btn-sm me-2">Editar</a>
                        <form action="{{ url_for('accesorio_bp.accesorio_eliminar', id=accesorio.id) }}" method="POST" class="d-inline">
                            <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                        </form>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/base_template.html
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="nav navbar-nav">
            <a class="nav-item nav-link active" href="/">Inicio</a>
            <a class="nav-item nav-link" href="/telefono_list">Telefonos</a>
            <a class="nav-item nav-link" href="/marca_list">Marca</a>
            <a class="nav-item nav-link" href="/tipo_list">Tipo</a>
            <a class="nav-item nav-link" href="/accesorios_list">Accesorios</a>
            <a class="nav-item nav-link" href="../stock">Stock</a>


        </div>
    </nav>
    {% block content %}{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base_template.html' %}

{% block content %}
    <h1>Bienvenido a Mobiletech</h1>
{% endblock %}

templates/marca_edit.html
{% extends 'base_template.html' %}

{% block content %}
    <h4>Edite la Marca</h4>
    <form action="" method="post">
        <input type="text" name="nombre" value="{{marca.nombre}}">
        <button type="submit">Editar</button>
    </form>
{% endblock %}

templates/marca_list.html
{% extends 'base_template.html' %}

{% block content %}
<div class="container">
    <div class="row">

        <div class="col-md-6">
            <h4>Crear una nueva Marca</h4>
            <form action="" method="post">
                {{ formulario.hidden_tag() }}
                <div class="mb-3">
                    {{ formulario.nombre(class="form-control", placeholder="Nombre de la marca") }}
                </div>
                <button type="submit" class="btn btn-success">Guardar</button>
            </form>
        </div>

        <div class="col-md-6">
            <h4>Listado de Marcas</h4>
            <ul class="list-group">
                {% for marca in marcas %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="/marca/{{marca.id}}/telefonos" class="me-3">{{ marca.nombre }}</a>
                    <div>
                        <a href="/marca/{{ marca.id }}/editar" class="btn btn-warning btn-sm">Editar</a>
                        
                    </li>
                {% endfor %}
            </ul>
        </div>

    </div>
</div>
{% endblock %}

templates/stock.html
{% extends 'base_template.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>Stock de Teléfonos</h4>
            <ul class="list-group">
                {% for item in telefonos %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <span class="badge bg-primary me-2">{{ item.stock }} unidades</span>
                        {{ item.telefono.modelo }} / {{ item.telefono.marca.nombre }}
                    </div>

                    <form action="{{ url_for('stock.stock') }}" method="POST" class="d-flex align-items-center">
                        <input type="hidden" name="telefono_id" value="{{ item.telefono.id }}">

                        <div class="input-group me-2">
                            <input type="number" id="cantidad_{{ item.telefono.id }}" name="cantidad" class="form-control" placeholder="Cantidad"
                                aria-label="Cantidad" required>

                            <button class="btn btn-outline-danger" type="submit" name="accion" value="restar"
                                onclick="convertToNegative({{ item.telefono.id }})">Eliminar</button>

                            <button class="btn btn-outline-success" type="submit" name="accion" value="agregar">Agregar</button>
                        </div>
                    </form>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<script>
    function convertToNegative(telefonoId) {
        var inputField = document.getElementById('cantidad_' + telefonoId);
        var value = parseInt(inputField.value);

        if (value > 0) {
            inputField.value = -Math.abs(value);
        }
    }
</script>
{% endblock %}

templates/telefono_list.html
{% extends 'base_template.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>Crear un nuevo Teléfono</h4>
            <form action="" method="POST">
                {{ formulario.hidden_tag() }}
                <div class="mb-3">
                    {{ formulario.modelo.label }} 
                    {{ formulario.modelo(class="form-control mb-2") }}
                    {{ formulario.precio.label }} 
                    {{ formulario.precio(class="form-control mb-2") }}
                    {{ formulario.anio_fabricacion.label }} 
                    {{ formulario.anio_fabricacion(class="form-control mb-2") }}
                    
                    {{ formulario.accesorio.label }} 
                    {{ formulario.accesorio(class="form-control mb-2") }}
                    
                    {{ formulario.marca.label }} 
                    {{ formulario.marca(class="form-control mb-2") }}
                    
                    {{ formulario.tipo.label }} 
                    {{ formulario.tipo(class="form-control mb-2") }}
                </div>
                <button type="submit" class="btn btn-success">Guardar</button>
            </form>
                    </div>

        <div class="col-md-6">
            <h4>Listado de Teléfonos</h4>
            <ul class="list-group">
                {% for telefono in telefonos %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <a href="{{ url_for('telefono.telefono_accesorio', id=telefono.id) }}" class="me-3">
                            {{ telefono.modelo }} - {{ telefono.precio }} - {{ telefono.anio_fabricacion }} - {{ telefono.marca.nombre }} - {{ telefono.tipo.nombre }}
                        </a>
                    </div>
                    <div>
                        <form action="{{ url_for('telefono.telefono_eliminar', id=telefono.id) }}" method="POST" class="d-inline">
                            <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                        </form>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/telefonos_by_marca.html
{% extends 'base_template.html' %}

{% block content %}
<h4>Listado de telefonos de la marca {{marca}}</h4>
    {% for telefono in telefonos %}
        <li> {{telefono.modelo}} - {{telefono.precio}} -{{telefono.anio_fabricacion}} -{{telefono.marca}} - {{telefono.tipo.nombre}} </li>
    {% endfor %}
{% endblock %}

templates/tipo_list.html
{% extends 'base_template.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>Crear un nuevo Tipo</h4>
            <form action="{{ url_for('tipo.tipos') }}" method="POST">
                {{ formulario.hidden_tag() }}  
                <div class="mb-3">
                    {{ formulario.nombre.label }}
                    {{ formulario.nombre(class="form-control", placeholder="Nombre del tipo") }}
                </div>
                <button type="submit" class="btn btn-success">Guardar</button>
            </form>
            
        </div>

        <div class="col-md-6">
            <h4>Listado de Tipos</h4>
            <ul class="list-group">
                {% for tipo in tipos %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <a href="/tipo/{{tipo.id}}/telefonos" class="me-3">{{ tipo.nombre }}</a>
                    </div>
                    <div>
                        <a href="/tipo/{{ tipo.id }}/editar" class="btn btn-warning btn-sm me-2">Editar</a>
                        <form action="{{ url_for('tipo.tipo_eliminar', id=tipo.id) }}" method="POST" class="d-inline">
                            <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                        </form>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}